# Generated by Django 4.2.5 on 2024-03-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='capacity',
        ),
        migrations.AddField(
            model_name='reservation',
            name='capacity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
