# Generated by Django 4.2.5 on 2024-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_room_capacity_reservation_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='capacity',
            new_name='people_of_attends',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
