# Generated by Django 4.2.5 on 2024-03-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_capacity_reservation_people_of_attends_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='people_of_attends',
            new_name='remaining_seats',
        ),
    ]
