# Generated by Django 4.2.5 on 2024-03-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_room_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='booked',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
